# Generated by Django 5.2.11 on 2026-02-12 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('base_points', models.IntegerField(default=10, verbose_name='基準ポイント')),
                ('difficulty', models.IntegerField(choices=[(1, '簡単 (1)'), (2, '普通 (2)'), (3, '少し大変 (3)'), (4, '大変 (4)'), (5, 'すごく大変 (5)')], default=2, verbose_name='難易度')),
                ('attributes', models.JSONField(blank=True, default=list, verbose_name='属性タグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='accounts.housegroup')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chores', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='ChoreExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完了日時')),
                ('points_earned', models.IntegerField(verbose_name='獲得ポイント')),
                ('status', models.CharField(choices=[('PENDING', '承認待ち'), ('APPROVED', '完了'), ('REJECTED', '却下')], default='APPROVED', max_length=10)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='chores.chore')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
            ],
        ),
    ]
